### PR TITLE
Associate ACM cert with ALB and update SG

### PR DESCRIPTION
**Pull request by jmvbxx**
🤞

### CODE REVIEW

**Comment by jmvbxx** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place

Terraform will perform the following actions:

  # aws_lb_listener.lb_listener will be updated in-place
~ resource "aws_lb_listener" "lb_listener" {
        id                = "arn:aws:elasticloadbalancing:us-east-1:096370227225:listener/app/atlantis-lb-tf/4b8c24863f4c2a19/1ba460f7716b4b87"
      ~ port              = 80 -> 443
      ~ protocol          = "HTTP" -> "HTTPS"
        tags              = {}
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # aws_lb_listener_certificate.example will be created
+ resource "aws_lb_listener_certificate" "example" {
      + certificate_arn = "arn:aws:acm:us-east-1:096370227225:certificate/380412dd-8e82-4020-a667-639a1ff1f791"
      + id              = (known after apply)
      + listener_arn    = "arn:aws:elasticloadbalancing:us-east-1:096370227225:listener/app/atlantis-lb-tf/4b8c24863f4c2a19/1ba460f7716b4b87"
    }

  # aws_security_group.allow_atlantis will be updated in-place
~ resource "aws_security_group" "allow_atlantis" {
        id                     = "sg-0d3ffc63bdbdbc728"
      ~ ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "443 from world"
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
            # (2 unchanged elements hidden)
        ]
        name                   = "allow_atlantis"
        tags                   = {}
        # (7 unchanged attributes hidden)
    }

Plan: 1 to add, 2 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.jmvbxx.com/lock?id=jmvbxx%252Fatlantis-ansible%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 2 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by jmvbxx** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
~ update in-place

Terraform will perform the following actions:

  # aws_lb_listener.lb_listener will be updated in-place
~ resource "aws_lb_listener" "lb_listener" {
        id                = "arn:aws:elasticloadbalancing:us-east-1:096370227225:listener/app/atlantis-lb-tf/4b8c24863f4c2a19/1ba460f7716b4b87"
      ~ port              = 80 -> 443
      ~ protocol          = "HTTP" -> "HTTPS"
        tags              = {}
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

  # aws_lb_listener_certificate.atlantis_cert will be created
+ resource "aws_lb_listener_certificate" "atlantis_cert" {
      + certificate_arn = "arn:aws:acm:us-east-1:096370227225:certificate/380412dd-8e82-4020-a667-639a1ff1f791"
      + id              = (known after apply)
      + listener_arn    = "arn:aws:elasticloadbalancing:us-east-1:096370227225:listener/app/atlantis-lb-tf/4b8c24863f4c2a19/1ba460f7716b4b87"
    }

  # aws_security_group.allow_atlantis will be updated in-place
~ resource "aws_security_group" "allow_atlantis" {
        id                     = "sg-0d3ffc63bdbdbc728"
      ~ ingress                = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "443 from world"
              + from_port        = 443
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 443
            },
            # (2 unchanged elements hidden)
        ]
        name                   = "allow_atlantis"
        tags                   = {}
        # (7 unchanged attributes hidden)
    }

Plan: 1 to add, 2 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.jmvbxx.com/lock?id=jmvbxx%252Fatlantis-ansible%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 1 to add, 2 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by jmvbxx** [comment]
altantis apply

**Comment by jmvbxx** [comment]
Ran Plan for dir: `terraform` workspace: `default`

<details><summary>Show Output</summary>

```diff

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # aws_lb_listener.lb_listener has been changed
~ resource "aws_lb_listener" "lb_listener" {
        id                = "arn:aws:elasticloadbalancing:us-east-1:096370227225:listener/app/atlantis-lb-tf/4b8c24863f4c2a19/1ba460f7716b4b87"
      ~ port              = 443 -> 80
      ~ protocol          = "HTTPS" -> "HTTP"
        tags              = {}
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_lb_listener.lb_listener will be updated in-place
~ resource "aws_lb_listener" "lb_listener" {
      + certificate_arn   = "arn:aws:acm:us-east-1:096370227225:certificate/380412dd-8e82-4020-a667-639a1ff1f791"
        id                = "arn:aws:elasticloadbalancing:us-east-1:096370227225:listener/app/atlantis-lb-tf/4b8c24863f4c2a19/1ba460f7716b4b87"
      ~ port              = 80 -> 443
      ~ protocol          = "HTTP" -> "HTTPS"
        tags              = {}
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.jmvbxx.com/lock?id=jmvbxx%252Fatlantis-ansible%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`
</details>
Plan: 0 to add, 1 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by majormoses** [comment]
atlantis apply

**Comment by jmvbxx** [comment]
atlantis plan

**Comment by jmvbxx** [comment]
Ran Plan for dir: `terraform` workspace: `default`

```diff

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d terraform`
* :put_litter_in_its_place: To **delete** this plan click [here](https://atlantis.jmvbxx.com/lock?id=jmvbxx%252Fatlantis-ansible%252Fterraform%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d terraform`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by jmvbxx** [comment]
atlantis apply

**Comment by jmvbxx** [comment]
Ran Apply for dir: `terraform` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

**Comment by jmvbxx** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by jmvbxx** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `terraform` workspace: `default`

**Pull request merged**
